logging:
    version : 1
    disable_existing_loggers: False
    formatters:
        simpleFormater:
            format: '[%(asctime)s,%(msecs)d] %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: INFO
    root:
        level: DEBUG
        handlers: [console]